version: '3'
services:
  elasticsearch:
    build: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    expose:
      -  9300
    networks:
      - elastic

  kibana:
    build: kibana
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:

volumes:
  elasticsearch-data:
    driver: local